import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { pageContent, pageTitles } from '../pageContent';
export default function ContentPage({page}){ const ref=useRef(null); const navigate=useNavigate(); const [notice,setNotice]=useState('');
 useEffect(()=>{document.title=pageTitles[page]||'S.O.S Focinho Carente'; const root=ref.current;if(!root)return;
  const onClick=e=>{const link=e.target.closest('a');if(link){const href=link.getAttribute('href');if(href?.startsWith('/')){e.preventDefault();navigate(href)}} const q=e.target.closest('.faq-question');if(q){const answer=q.closest('.faq-item')?.querySelector('.faq-answer');const open=q.getAttribute('aria-expanded')==='true';q.setAttribute('aria-expanded',String(!open));if(answer)answer.style.maxHeight=open?'0px':answer.scrollHeight+'px'} const f=e.target.closest('.filter-btn');if(f){root.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));f.classList.add('active');const filter=f.dataset.filter;root.querySelectorAll('[data-category]').forEach(card=>card.hidden=!(filter==='all'||card.dataset.category?.split(' ').includes(filter)));}};
  const onSubmit=e=>{e.preventDefault();const form=e.target;if(form.matches('#contactForm')){setNotice('Mensagem preparada. Conecte este formulário ao seu serviço de envio para colocá-lo em produção.');form.reset()}else if(form.matches('.footer-newsletter-form')){setNotice('Inscrição registrada na interface. Conecte um serviço de newsletter para produção.');form.reset()}};
  root.addEventListener('click',onClick);root.addEventListener('submit',onSubmit);return()=>{root.removeEventListener('click',onClick);root.removeEventListener('submit',onSubmit)}} ,[page,navigate]);
 return <>{notice&&<div className="app-notice" role="status"><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="Fechar aviso">×</button></div>}<div ref={ref} className={`page page-${page}`} dangerouslySetInnerHTML={{__html:pageContent[page]}}/></> }
