import { useEffect, useState } from 'react';
import { NavLink, Link } from 'react-router-dom';
const nav = [['/', 'Início'], ['/sobre', 'Sobre'], ['/adocao', 'Adoção'], ['/brecho', 'Brechó'], ['/eventos', 'Eventos'], ['/como-ajudar', 'Como Ajudar'], ['/noticias', 'Notícias'], ['/galeria', 'Galeria'], ['/contato', 'Contato']];
function preferredTheme() { const saved = localStorage.getItem('theme'); return saved || (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'); }
export default function Layout({ children }) {
    const [menu, setMenu] = useState(false); const [theme, setTheme] = useState(preferredTheme); const [scrolled, setScrolled] = useState(false); const [top, setTop] = useState(false);
    useEffect(() => { document.documentElement.dataset.theme = theme === 'dark' ? 'dark' : ''; localStorage.setItem('theme', theme) }, [theme]);
    useEffect(() => { const on = () => { setScrolled(scrollY > 50); setTop(scrollY > 400) }; on(); addEventListener('scroll', on, { passive: true }); return () => removeEventListener('scroll', on) }, []);
    useEffect(() => { document.body.style.overflow = menu ? 'hidden' : ''; const esc = e => e.key === 'Escape' && setMenu(false); addEventListener('keydown', esc); return () => { removeEventListener('keydown', esc); document.body.style.overflow = '' } }, [menu]);
    return <><a className="skip-link" href="#conteudo">Pular para o conteúdo</a><header className={`header ${scrolled ? 'scrolled' : ''}`}><div className="container"><div className="header-inner">
        <Link to="/" className="logo" aria-label="S.O.S Focinho Carente — Página inicial"><span className="logo-mark" aria-hidden="true"><i className="fas fa-paw" /></span><span><span className="text-gradient">S.O.S</span> Focinho Carente</span></Link>
        <nav className="nav" aria-label="Navegação principal"><div className={`nav-overlay ${menu ? 'active' : ''}`} onClick={() => setMenu(false)} /><ul className={`nav-list ${menu ? 'open' : ''}`} id="navList">{nav.map(([to, label]) => <li key={to}><NavLink end={to === '/'} to={to} onClick={() => setMenu(false)} className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`}>{label}</NavLink></li>)}<li><NavLink to="/contato" className="btn-nav" onClick={() => setMenu(false)}><i className="fas fa-heart" aria-hidden="true" /> Doe</NavLink></li></ul></nav>
        <button className="theme-toggle" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} aria-label={theme === 'dark' ? 'Ativar modo claro' : 'Ativar modo escuro'} aria-pressed={theme === 'dark'}><i className={`fas ${theme === 'dark' ? 'fa-sun' : 'fa-moon'}`} /></button>
        <button className={`menu-toggle ${menu ? 'active' : ''}`} onClick={() => setMenu(!menu)} aria-label={menu ? 'Fechar menu' : 'Abrir menu'} aria-expanded={menu} aria-controls="navList"><span /><span /><span /></button>
    </div></div></header><main id="conteudo">{children}</main><Footer /><div className="social-float"><a href="https://wa.me/5514997717449" target="_blank" rel="noopener noreferrer" className="wa" aria-label="WhatsApp"><i className="fab fa-whatsapp" /></a><a href="https://www.instagram.com/adoteumfocinhocarente/" target="_blank" rel="noopener noreferrer" className="ig" aria-label="Instagram"><i className="fab fa-instagram" /></a></div><button className={`back-top ${top ? 'visible' : ''}`} onClick={() => scrollTo({ top: 0, behavior: 'smooth' })} aria-label="Voltar ao topo"><i className="fas fa-chevron-up" /></button></>;
}
function Footer() { return <footer className="footer"><div className="container"><div className="footer-grid"><div className="footer-brand"><Link to="/" className="logo"><span className="logo-mark"><i className="fas fa-paw" /></span><span><span className="text-gradient">S.O.S</span> Focinho Carente</span></Link><p>ONG dedicada ao resgate, proteção e bem-estar animal. Entidade sem fins lucrativos fundada em 2019 em Barra Bonita, SP.</p><div className="footer-social"><a href="https://www.instagram.com/adoteumfocinhocarente/" target="_blank" rel="noopener noreferrer" aria-label="Instagram"><i className="fab fa-instagram" /></a><a href="https://www.facebook.com/focinho.carente.9" target="_blank" rel="noopener noreferrer" aria-label="Facebook"><i className="fab fa-facebook-f" /></a><a href="https://wa.me/5514997717449" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp"><i className="fab fa-whatsapp" /></a></div></div><div><h4>Links</h4><ul className="footer-links">{nav.map(([to, l]) => <li key={to}><Link to={to}>{l}</Link></li>)}</ul></div><div><h4>Serviços</h4><ul className="footer-links"><li><Link to="/adocao">Adoção</Link></li><li><Link to="/como-ajudar">Doações</Link></li><li><Link to="/como-ajudar">Voluntariado</Link></li><li><Link to="/brecho">Brechó</Link></li></ul></div><div><h4>Contato</h4><ul className="footer-contact"><li><i className="fas fa-map-marker-alt" /><span>Rua Augusto da Silva, 352 — Jardim Nova Barra, Barra Bonita, SP</span></li><li><i className="fas fa-phone" /><span>(14) 99771-7449</span></li><li><i className="fas fa-envelope" /><span>contato@sosfocinhocarente.com.br</span></li></ul></div></div><div className="footer-bottom"><p>© 2026 S.O.S Focinho Carente. Todos os direitos reservados.</p><p>CNPJ: 34.838.740/0001-13</p></div></div></footer> }
